### ISSUE TITLE
failed "make install" on Ubuntu 18.04

### ISSUE THREAD

**Issue by legluondunet** [voyageur/openglide#11]
Hello,
I tried today to compile openglide from source on Ubuntu 18.04.
Compilation finished without error but "make install" failed at install libopenglide.so.2 step:
```

make[3] : on entre dans le répertoire « /home/legluondunet/Bureau/openglide »
cd /usr/local/lib && \
	ln -s -f lib*.so libglide.so.2
ln: 'libglide.so.2' is not a directory
Makefile:1110: recipe for target 'install-exec-hook' failed
make[3]: *** [install-exec-hook] Error 1
```

I joined you the log.
Thank you for your help.

[openglide_compil_ubuntu_18.04.log](https://github.com/voyageur/openglide/files/3846199/openglide_compil_ubuntu_18.04.log)

**Comment by chewi** [comment]
#12 fixes this.

**Comment by voyageur** [comment]
Sorry about that, @chewi 's fix will indeed help here (and avoid potentially interesting issues in install too)
