### ISSUE TITLE
Can't compile on Debian buster

### ISSUE THREAD

**Issue by t9999clint** [voyageur/openglide#21]
there's not configure file and make doesn't work.
Autoconf and automake also do nothing.

Is there some documentation that I'm missing? I can't figure it out

**Comment by voyageur** [comment]
You may be missing some autotools packages? autoconf/automake/libtool/etc

There is no committed configure script as it should be easily recreatable (if this is a word): either the bootstrap script or "autoreconf -vi" should do the trick

**Comment by t9999clint** [comment]
I totally missed the bootstrap script.
Thanks that worked fine.
IMHO you should probably update the readme.md to include quick compilation instructions as well as a list of potential dependencies

**Comment by voyageur** [comment]
> IMHO you should probably update the readme.md to include quick compilation instructions as well as a list of potential dependencies

Very good point, yes. Initially this was mostly intented as backup git repository for original sources, but it seems it is used by some! I will add some pointers to README.md
