### ISSUE TITLE
platform/dosbox/dosbox_glide.diff no longer applies to DOSBox git checkout

### ISSUE THREAD

**Issue by Sophira** [voyageur/openglide#9]
A change in DOSBox's `configure.ac` file on 10th October 2017 ( https://sourceforge.net/p/dosbox/code-0/4056/ ) means that the `platform/dosbox/dosbox_glide.diff` file in this project no longer cleanly applies; [the hunk that changes the LIBS line for Cygwin/mingw32 gets rejected](https://github.com/voyageur/openglide/blob/18645f2f50da4b83b7edf4556870e5c410a24428/platform/dosbox/dosbox_glide.diff#L53-L61).

At a glance, the fix appears to be fairly simple - just add the "-lshlwapi" flag back - but I don't know enough about the patch to know whether this will work or not, and I don't have the correct build environment for it.

**Comment by voyageur** [comment]
Thanks for the report, I will update the patch (I have a few demos lying around my dosbox directory so can test). I will also copy the original patch for people still using 0.74

**Comment by Sophira** [comment]
By the way, thank you for updating the Gentoo repository at the same time! This actually came about *because* I was using the live ebuild on Gentoo,  and [I had opened a bug for it there too](https://bugs.gentoo.org/show_bug.cgi?id=644176).

I've marked it RESOLVED FIXED now, but it seems rude to add others to CC, so wanted to make sure you saw my gratitude somehow. :D Thank you!

**Comment by voyageur** [comment]
No problem, the live Gentoo ebuild is the main reason for that patch being around, so better to have both working fine :)
